### PR TITLE
clc_server_fact returns `publicip` and `ipaddress` fields.

### PR DESCRIPTION
**Pull request by AdeMiller**
This adds `publicip` and `ipaddress` fields to the returned value for `clc_server_fact` so that is is (more or less) equivalent to `clc_server`. It make parsing the returned JSON for the server's IP address much simpler. I assume this was why it was added to `clc_server`.

Note: There are no unit tests for this as there are no test associated with `clc_server_fact` or `clc_group_fact`.

### CODE REVIEW

**Comment by markramach** [comment]
@AdeMiller How do we decide which IP address wins?

```
            "ipAddresses": [
                {
                    "internal": "10.122.35.23"
                }, 
                {
                    "internal": "10.122.35.38"
                }, 
                {
                    "internal": "10.122.35.39", 
                    "public": "64.15.190.86"
                }
            ], 
```

**Comment by AdeMiller** [comment]
The same way `clc_server` does:

```
                server.data['ipaddress'] = server.details[
                    'ipAddresses'][0]['internal']
                server.data['publicip'] = str(
                    server.PublicIPs().public_ips[0])
```

I just replicated this behavior - which I would argue is not ideal. But if it was sufficient for `clc_server` then it is no worse here. Not having this makes for some very painful Ansible filters which also would have no way of picking a particular IP address.

**Comment by markramach** [comment]
I didn't realize clc_server was returning both ipaddress and ipAddresses. This does appear to be consistent with that module. I'll go ahead and merge this.

**Comment by markramach** [comment]
@AdeMiller Actually, I'm going to close this. Can you create another pull request for the develop branch. We don't merge into master until release.

**Pull request closed without merging**
